# docker-compose.yml
version: '3'
services:
  postgres:
    image: postgres:13
    container_name: beskid-db
    environment:
      POSTGRES_USER: capitan
      POSTGRES_PASSWORD: loynis2007
      POSTGRES_DB: beskidgriezlies
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: